source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
#gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml'
gem 'jquery-turbolinks'
gem 'nokogiri'
gem 'execjs'
gem 'rails_admin'
gem 'paperclip'
gem 'ckeditor'
gem 'rails-i18n'
gem 'rails_admin-i18n'
gem 'russian'
gem 'rename'
gem 'globalize', '~> 4.0'
gem 'globalize-accessors'
gem 'rails_admin_globalize_field', github: 'VoroninNick/rails_admin_globalize_field', branch: 'allow-current-locale'
gem 'quiet_assets', group: :development
gem 'protected_attributes'
gem 'lograge'
gem 'logstash-event'
gem 'breadcrumbs_on_rails'
gem 'nprogress-rails'
gem 'mail_form'
gem 'will_paginate', '~> 3.0'
gem 'fancybox2-rails', '~> 0.2.8'
gem 'progress_bar'
gem 'sunspot_rails'
gem 'slim-rails'
gem 'simple_form'
gem "selectize-rails"
gem 'better_errors'
gem 'binding_of_caller'
gem 'nprogress-rails'
gem 'devise'
gem 'paper_trail', require: false
gem 'merit'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
#gem 'client_side_validations'

group :development do
  gem 'sunspot_solr'
end


